name: Auto Tag

on:
  push:
    branches: [develop, main]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the current version
        id: get_version
        run: echo "version=$(git describe --tags --abbrev=0 || echo '0.0.0')" >> $GITHUB_ENV

      - name: Create new version tag
        id: new_tag
        run: |
          new_version=$(echo ${{ env.version }} | awk -F. -v OFS=. '{$NF++;print}')
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ env.new_version }}
          git push origin ${{ env.new_version }}
