name: Deploy

on:
  workflow_call:

env:
  BUILD_DIR: build
  GITHUB_REF: ${{ github.ref }}
  GITHUB_BASE_REF: ${{ github.base_ref }}
  GITHUB_HEAD_REF: ${{ github.head_ref }}
  GITHUB_EVENT: ${{ github.event_name }}
  GITHUB_REPO: ${{github.repository }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install app dependencies
        run: |
          pip install -r requirements.txt

      - name: Stop venv
        run: |
          deactivate
