name: Build_and_deploy_on_PR

on:
  workflow_dispatch: {}
  pull_request:
    branches: [develop, main]
    types: [opened, edited]

jobs:
  build:
    if: ${{ github.event_name == 'pull_request' && github.actor == 'tuyojr' }}
    uses: tuyojr/flow_test/.github/workflows/build.yml@main
    secrets: inherit

  deploy:
    if: ${{ github.event_name == 'pull_request' && github.actor == 'tuyojr' }}
    uses: tuyojr/flow_test/.github/workflows/deploy.yml@main
    secrets: inherit
    needs: build
